from typing import Any, ClassVar, Protocol, runtime_checkable

from gb_types import Address, Byte, Cycles


@runtime_checkable
class MemoryBus(Protocol):
    storage: Any

    def read_byte(self, address: Address) -> Byte: ...
    def write_byte(self, address: Address, value: Byte) -> None: ...
    def request_interrupt(self, mask: Byte) -> None: ...


@runtime_checkable
class MemoryBankController(Protocol):
    rom: Any
    ram: Any
    ram_enabled: bool
    ram_dirty: bool
    on_bank_change: Any
    on_ram_bank_change: Any
    on_ram_write: Any

    def read_rom(self, address: Address) -> Byte: ...
    def write_rom(self, address: Address, value: Byte) -> None: ...
    def read_ram(self, address: Address) -> Byte: ...
    def write_ram(self, address: Address, value: Byte) -> None: ...
    def visible_ram_window(self) -> bytes: ...


@runtime_checkable
class VideoDevice(Protocol):
    frame_done: bool

    def read_byte(self, address: Address) -> Byte: ...
    def write_byte(self, address: Address, value: Byte) -> None: ...
    def step(self, cycles: Cycles) -> None: ...
    def perform_dma(self, value: Byte) -> None: ...


@runtime_checkable
class AudioDevice(Protocol):
    SAMPLE_RATE: ClassVar[int]
    buffer: Any
    buffer_read_pos: int
    buffer_write_pos: int
    buffer_size: int

    def read_byte(self, address: Address) -> Byte: ...
    def write_byte(self, address: Address, value: Byte) -> None: ...
    def step(self, cycles: Cycles) -> None: ...


@runtime_checkable
class InputDevice(Protocol):
    def read(self) -> Byte: ...
    def write(self, value: Byte) -> None: ...
    def set_key(self, key: str, pressed: bool) -> None: ...


@runtime_checkable
class SerialDevice(Protocol):
    def read_byte(self, address: Address) -> Byte: ...
    def write_byte(self, address: Address, value: Byte) -> None: ...


@runtime_checkable
class ClockDevice(Protocol):
    cycles_elapsed: Cycles

    def update(self, cycles: Cycles) -> None: ...
    def get_cycles_elapsed(self) -> Cycles: ...
    def wait_for_next_cycle(self, cycles: Cycles) -> None: ...
