from typing import Protocol, runtime_checkable, Any, Deque, ClassVar
from gb_types import Sample, Address, Byte, Cycles


@runtime_checkable
class MemoryBus(Protocol):
    storage: Any

    def read_byte(self, address: Address) -> Byte: ...
    def write_byte(self, address: Address, value: Byte) -> None: ...
    def request_interrupt(self, mask: Byte) -> None: ...


@runtime_checkable
class MemoryBankController(Protocol):
    def read_rom(self, address: Address) -> Byte: ...
    def write_rom(self, address: Address, value: Byte) -> None: ...
    def read_ram(self, address: Address) -> Byte: ...
    def write_ram(self, address: Address, value: Byte) -> None: ...


@runtime_checkable
class VideoDevice(Protocol):
    def read_byte(self, address: Address) -> Byte: ...
    def write_byte(self, address: Address, value: Byte) -> None: ...
    def step(self, cycles: Cycles) -> None: ...


@runtime_checkable
class AudioDevice(Protocol):
    SAMPLE_RATE: ClassVar[int]
    buffer: Deque[Sample]

    def read_byte(self, address: Address) -> Byte: ...
    def write_byte(self, address: Address, value: Byte) -> None: ...
    def step(self, cycles: Cycles) -> None: ...


@runtime_checkable
class InputDevice(Protocol):
    def read(self) -> Byte: ...
    def write(self, value: Byte) -> None: ...
    def set_key(self, key: str, pressed: bool) -> None: ...


@runtime_checkable
class SerialDevice(Protocol):
    def read_byte(self, address: Address) -> Byte: ...
    def write_byte(self, address: Address, value: Byte) -> None: ...


@runtime_checkable
class ClockDevice(Protocol):
    def update(self, cycles: Cycles) -> None: ...
    def get_cycles_elapsed(self) -> Cycles: ...
    def wait_for_next_cycle(self, cycles: Cycles) -> None: ...
