from typing import Protocol, runtime_checkable, Union, Optional

@runtime_checkable
class MemoryBankController(Protocol):
    def read_rom(self, address: int) -> int: ...
    def write_rom(self, address: int, value: int) -> None: ...
    def read_ram(self, address: int) -> int: ...
    def write_ram(self, address: int, value: int) -> None: ...

@runtime_checkable
class VideoDevice(Protocol):
    def read_byte(self, address: int) -> int: ...
    def write_byte(self, address: int, value: int) -> None: ...
    def step(self, cycles: int) -> None: ...

@runtime_checkable
class AudioDevice(Protocol):
    def read_byte(self, address: int) -> int: ...
    def write_byte(self, address: int, value: int) -> None: ...
    def step(self, cycles: int) -> None: ...

@runtime_checkable
class InputDevice(Protocol):
    def read(self) -> int: ...
    def write(self, value: int) -> None: ...
    def set_key(self, key: str, pressed: bool) -> None: ...

@runtime_checkable
class SerialDevice(Protocol):
    def read_byte(self, address: int) -> int: ...
    def write_byte(self, address: int, value: int) -> None: ...

@runtime_checkable
class ClockDevice(Protocol):
    def update(self, cycles: int) -> None: ...
    def get_cycles_elapsed(self) -> int: ...
